---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipemanager-sergiotejon-github-io-v1alpha1-pipeline
  failurePolicy: Fail
  name: mpipeline-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipemanager.sergiotejon.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipemanager-sergiotejon-github-io-v1alpha1-pipeline
  failurePolicy: Fail
  name: vpipeline-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipemanager.sergiotejon.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
