common:
  log:
    level: "debug"
    file: "stdout"
    format: "text"

launcher:
  imageName: "k3d-registry:5111/launcher"
  pullPolicy: "IfNotPresent"
  tag: ""

  namespace: "pipe-manager"
  jobNamePrefix: "pipeline-launcher"
  timeout: 600
  backoffLimit: 2
  cloneDepth: 1

  pipelineType: "tekton"

  rolesBinding: []

  artifactsBucket:
    url: "s3://pipe-manager/artifacts"
    basePath: "pipe-manager"
    parameters:
      endpoint: "localhost:9000"
      disableSSL: "true"
      s3ForcePathStyle: "true"
      awssdk: "v1"
    credentials:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: "s3-credentials"
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "s3-credentials"
              key: aws_secret_access_key
      volumes:
        - name: s3-credentials
          secret:
            secretName: "s3-credentials"
      volumeMounts:
        - name: s3-credentials
          mountPath: "/etc/s3-credentials"
          readOnly: true

  configmapName: "pipeline-launcher-config"
